package lab0a;

/**
 *
 * @author levenick
 */
public class Lab0aFrame extends javax.swing.JFrame {

    private DisplayFrame otherFrame;

    public Lab0aFrame() {
        initComponents();
        fillBox();
        makeTheOtherFrame();
        setTitle("Lab0a");

        this.setSize(500, 500);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        theTA = new javax.swing.JTextArea();
        theComboBox = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        theTA.setColumns(20);
        theTA.setRows(5);
        theTA.setText("1 2 3\n\n4\n\n5      6   8  9  5 4 6  2 3 6\n\n4 4\n");
        jScrollPane1.setViewportView(theTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 200, 280);

        theComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        theComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(theComboBox);
        theComboBox.setBounds(236, 50, 130, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void theComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theComboBoxActionPerformed
        System.out.println("in action performed");
        if (theComboBox.getSelectedItem() == null) {
            System.out.println("oops");
            return;
        }
        String s = (String) theComboBox.getSelectedItem();
        System.out.println("s = " + s);
        if (otherFrame == null) {
            return;
        }
        otherFrame.go(Integer.parseInt(s), theTA.getText());
    }//GEN-LAST:event_theComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab0aFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab0aFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab0aFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab0aFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab0aFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> theComboBox;
    private javax.swing.JTextArea theTA;
    // End of variables declaration//GEN-END:variables

    // Fill combo box with right values
    private void fillBox() {
        theComboBox.removeAllItems();
        for (int i = 1; i <= 10; i++) {
            theComboBox.addItem("" + i);
        }
    }
    
    
    private void makeTheOtherFrame() {
        otherFrame = new DisplayFrame();
    }
}
