/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragrace;

import static dragrace.Controller.column;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author marco
 */
public class RacePanel extends javax.swing.JPanel {

    public RacePanel() {
        initComponents();
        setLayout(null);
        setVisible(true);
        setSize(500, 500);

        // set Controller
        Controller c = new Controller(this);
    }

    @Override
    public void paintComponent(Graphics g) {
        if (g == null) {
            return;
        }

        super.paintComponent(g);
        ImageIcon image = new ImageIcon(new ImageIcon(getClass().getResource("images/car1.png")).getImage());

        g.drawImage(image.getImage(), column, 195, 60, 30, null);

        ImageIcon image2 = new ImageIcon(new ImageIcon(getClass().getResource("images/car3.png")).getImage());

        g.drawImage(image2.getImage(), column, 90, 60, 30, null);

        ImageIcon image3 = new ImageIcon(new ImageIcon(getClass().getResource("images/car6.png")).getImage());

        g.drawImage(image3.getImage(), column, 260, 60, 30, null);

        g.setColor(Color.WHITE);
        
        System.out.println(column);
        if (column >= 1000) {
            toggle(); 
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    void go() {
        Controller.move();
    }

    void toggle() {
        Controller.toggleRunning();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
