/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragrace;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author marco
 */
public class RacePanel extends javax.swing.JPanel {

    public RacePanel() {
        initComponents();
        setLayout(null);
        setVisible(true);
        setPreferredSize(new Dimension(2000, 2000));
    }

    public void paintComponect(Graphics g) {
        if (g == null) {
            return;
        }

        super.paintComponent(g);
        g.setColor(Color.RED);
        g.fillOval(80, 30, 50, 90);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    void go() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
