/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package montehall;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author marco
 */
public class MonteFrame extends javax.swing.JFrame {

    MontePlay play = new MontePlay();
    List<Boolean> doors = new ArrayList<Boolean>();

    public MonteFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        door1 = new javax.swing.JButton();
        door2 = new javax.swing.JButton();
        door3 = new javax.swing.JButton();
        textField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        door1.setText("Door 1");
        door1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                door1ActionPerformed(evt);
            }
        });
        getContentPane().add(door1);
        door1.setBounds(40, 30, 100, 160);

        door2.setText("Door 2");
        getContentPane().add(door2);
        door2.setBounds(170, 30, 100, 160);

        door3.setText("Door 3");
        getContentPane().add(door3);
        door3.setBounds(290, 30, 100, 160);
        getContentPane().add(textField);
        textField.setBounds(130, 270, 300, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void door1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_door1ActionPerformed
        // TODO add your handling code here:
        doors = play.selectDoor(0);
        System.out.println("Button 1 was clicked!");
        System.out.println(doors.toString());

        if (play.getDonkeyDoor() == 1) {
            door2.setEnabled(false);
        } else if (play.getDonkeyDoor() == 2) {
            door3.setEnabled(false);
        }
        textField.setText("Donkey behind door number " + (play.getDonkeyDoor() + 1));

    }//GEN-LAST:event_door1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton door1;
    private javax.swing.JButton door2;
    private javax.swing.JButton door3;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
